def print_compat_runner_module_source(
    module_name: str = "Generated.RunCompatCheck",
    old_api_module_name: str = "Generated.GeneratedOldAPI",
    new_api_module_name: str = "Generated.GeneratedNewAPI",
    old_api_name: str = "OldAPI",
    new_api_name: str = "NewAPI",
) -> str:
    lines = [
        f"module {module_name} where",
        "",
        "open import Agda.Builtin.IO",
        "import Agda.Builtin.Unit as Unit",
        "",
        "open import Prelude using (String; _∔_; List; []; _::_; inl; inr)",
        "open import Syntax.Syntax",
        f"open import {old_api_module_name}",
        f"open import {new_api_module_name}",
        "open import WellFormed.Core",
        "open import WellFormed.Decidable",
        "open import WellFormed.IllFormed",
        "open import Semantics.APIRefinement",
        "open import Semantics.DecidableRefinement",
        "open import Semantics.Drift",
        "",
        f"oldWF : WFAPI {old_api_name} ∔ APIIllFormed {old_api_name}",
        f"oldWF = WFAPI? {old_api_name}",
        "",
        f"newWF : WFAPI {new_api_name} ∔ APIIllFormed {new_api_name}",
        f"newWF = WFAPI? {new_api_name}",
        "",
        "methodToString : Method → String",
        "methodToString GET = \"GET\"",
        "methodToString POST = \"POST\"",
        "methodToString PUT = \"PUT\"",
        "methodToString DELETE = \"DELETE\"",
        "methodToString PATCH = \"PATCH\"",
        "",
        "statusToString : Status → String",
        "statusToString OK = \"OK\"",
        "statusToString BadRequest = \"BadRequest\"",
        "statusToString NotFound = \"NotFound\"",
        "statusToString NoContent = \"NoContent\"",
        "",
        "pathHeadToString : List PathSegment → String",
        "pathHeadToString [] = \"\"",
        "pathHeadToString (lit s :: _) = s",
        "pathHeadToString (param s :: _) = s",
        "",
        "pathHint : Path → String",
        "pathHint p = pathHeadToString (Path.segments p)",
        "",
        "",
        "schemaDriftKind : ∀ {s t} → SchemaDrift s t → String",
        "schemaDriftKind (PrimitiveChanged _ _ _) = \"primitive_changed\"",
        "schemaDriftKind (ArrayItemDrift _ _ _ _ _) = \"array_item_drift\"",
        "schemaDriftKind (RequiredFieldRemoved _ _ _ _) = \"required_field_removed\"",
        "schemaDriftKind (PropertyRemoved _ _ _ _) = \"property_removed\"",
        "schemaDriftKind (PropertyDrift _ _ _ _ _) = \"property_drift\"",
        "schemaDriftKind (ShapeMismatch _) = \"shape_mismatch\"",
        "",
        "schemaDriftCtxK : ∀ {s t} → SchemaDrift s t → String",
        "schemaDriftCtxK (PrimitiveChanged _ _ _) = \"type_change\"",
        "schemaDriftCtxK (ArrayItemDrift _ _ _ _ d) = schemaDriftCtxK d",
        "schemaDriftCtxK (RequiredFieldRemoved _ _ _ _) = \"required_field\"",
        "schemaDriftCtxK (PropertyRemoved _ _ _ _) = \"property\"",
        "schemaDriftCtxK (PropertyDrift _ _ _ _ _) = \"property\"",
        "schemaDriftCtxK (ShapeMismatch _) = \"type_change\"",
        "",
        "schemaDriftCtxV : ∀ {s t} → SchemaDrift s t → String",
        "schemaDriftCtxV (PrimitiveChanged _ _ _) = \"primitive_changed\"",
        "schemaDriftCtxV (ArrayItemDrift _ _ _ _ d) = schemaDriftCtxV d",
        "schemaDriftCtxV (RequiredFieldRemoved {k = k} _ _ _ _) = k",
        "schemaDriftCtxV (PropertyRemoved {k = k} _ _ _ _) = k",
        "schemaDriftCtxV (PropertyDrift {k = k} _ _ _ _ _) = k",
        "schemaDriftCtxV (ShapeMismatch _) = \"shape_mismatch\"",
        "",
        "compatTag : String",
        "compatTag with oldWF | newWF",
        "... | inr _ | _ = \"COMPAT_CHECK_ERROR:OLD_SPEC_NOT_WF\"",
        "... | _ | inr _ = \"COMPAT_CHECK_ERROR:NEW_SPEC_NOT_WF\"",
        f"... | inl wfOld | inl wfNew with API⊑? {old_api_name} {new_api_name} wfOld wfNew",
        "... | inl _ = \"COMPAT_OK\"",
        "... | inr (ComponentRemoved _ _) = \"COMPAT_ERR:COMPONENT_REMOVED\"",
        "... | inr (ComponentDriftWitness _ _ (PrimitiveChanged _ _ _)) = \"COMPAT_ERR:COMPONENT_SCHEMA_PRIMITIVE_CHANGED\"",
        "... | inr (ComponentDriftWitness _ _ (ArrayItemDrift _ _ _ _ _)) = \"COMPAT_ERR:COMPONENT_SCHEMA_ARRAY_ITEM_DRIFT\"",
        "... | inr (ComponentDriftWitness _ _ (RequiredFieldRemoved _ _ _ _)) = \"COMPAT_ERR:COMPONENT_SCHEMA_REQUIRED_FIELD_REMOVED\"",
        "... | inr (ComponentDriftWitness _ _ (PropertyRemoved _ _ _ _)) = \"COMPAT_ERR:COMPONENT_SCHEMA_PROPERTY_REMOVED\"",
        "... | inr (ComponentDriftWitness _ _ (PropertyDrift _ _ _ _ _)) = \"COMPAT_ERR:COMPONENT_SCHEMA_PROPERTY_DRIFT\"",
        "... | inr (ComponentDriftWitness _ _ (ShapeMismatch _)) = \"COMPAT_ERR:COMPONENT_SCHEMA_SHAPE_MISMATCH\"",
        "... | inr (ComponentDriftWitness _ _ _) = \"COMPAT_ERR:COMPONENT_DRIFT\"",
        "... | inr (EndpointRemoved _ _) = \"COMPAT_ERR:ENDPOINT_REMOVED\"",
        "... | inr (EndpointDriftWitness _ _ (RouteChanged _)) = \"COMPAT_ERR:ENDPOINT_ROUTE_CHANGED\"",
        "... | inr (EndpointDriftWitness _ _ (MethodChanged _)) = \"COMPAT_ERR:ENDPOINT_METHOD_CHANGED\"",
        "... | inr (EndpointDriftWitness _ _ (ParameterRemoved _ _)) = \"COMPAT_ERR:ENDPOINT_PARAMETER_REMOVED\"",
        "... | inr (EndpointDriftWitness _ _ (RequiredParameterAdded _ _ _ _ _ _)) = \"COMPAT_ERR:ENDPOINT_REQUIRED_PARAMETER_ADDED\"",
        "... | inr (EndpointDriftWitness _ _ (NewRequiredParameter _ _ _)) = \"COMPAT_ERR:ENDPOINT_NEW_REQUIRED_PARAMETER\"",
        "... | inr (EndpointDriftWitness _ _ (ParameterSchemaChanged _ _ _ _ _)) = \"COMPAT_ERR:ENDPOINT_PARAMETER_SCHEMA_CHANGED\"",
        "... | inr (EndpointDriftWitness _ _ (BodySchemaDrift _ _ (PrimitiveChanged _ _ _))) = \"COMPAT_ERR:ENDPOINT_BODY_SCHEMA_PRIMITIVE_CHANGED\"",
        "... | inr (EndpointDriftWitness _ _ (BodySchemaDrift _ _ (ArrayItemDrift _ _ _ _ _))) = \"COMPAT_ERR:ENDPOINT_BODY_SCHEMA_ARRAY_ITEM_DRIFT\"",
        "... | inr (EndpointDriftWitness _ _ (BodySchemaDrift _ _ (RequiredFieldRemoved _ _ _ _))) = \"COMPAT_ERR:ENDPOINT_BODY_SCHEMA_REQUIRED_FIELD_REMOVED\"",
        "... | inr (EndpointDriftWitness _ _ (BodySchemaDrift _ _ (PropertyRemoved _ _ _ _))) = \"COMPAT_ERR:ENDPOINT_BODY_SCHEMA_PROPERTY_REMOVED\"",
        "... | inr (EndpointDriftWitness _ _ (BodySchemaDrift _ _ (PropertyDrift _ _ _ _ _))) = \"COMPAT_ERR:ENDPOINT_BODY_SCHEMA_PROPERTY_DRIFT\"",
        "... | inr (EndpointDriftWitness _ _ (BodySchemaDrift _ _ (ShapeMismatch _))) = \"COMPAT_ERR:ENDPOINT_BODY_SCHEMA_SHAPE_MISMATCH\"",
        "... | inr (EndpointDriftWitness _ _ (ResponseRemoved _ _)) = \"COMPAT_ERR:ENDPOINT_RESPONSE_REMOVED\"",
        "... | inr (EndpointDriftWitness _ _ (ResponseDrift _ _ (PrimitiveChanged _ _ _))) = \"COMPAT_ERR:ENDPOINT_RESPONSE_SCHEMA_PRIMITIVE_CHANGED\"",
        "... | inr (EndpointDriftWitness _ _ (ResponseDrift _ _ (ArrayItemDrift _ _ _ _ _))) = \"COMPAT_ERR:ENDPOINT_RESPONSE_SCHEMA_ARRAY_ITEM_DRIFT\"",
        "... | inr (EndpointDriftWitness _ _ (ResponseDrift _ _ (RequiredFieldRemoved _ _ _ _))) = \"COMPAT_ERR:ENDPOINT_RESPONSE_SCHEMA_REQUIRED_FIELD_REMOVED\"",
        "... | inr (EndpointDriftWitness _ _ (ResponseDrift _ _ (PropertyRemoved _ _ _ _))) = \"COMPAT_ERR:ENDPOINT_RESPONSE_SCHEMA_PROPERTY_REMOVED\"",
        "... | inr (EndpointDriftWitness _ _ (ResponseDrift _ _ (PropertyDrift _ _ _ _ _))) = \"COMPAT_ERR:ENDPOINT_RESPONSE_SCHEMA_PROPERTY_DRIFT\"",
        "... | inr (EndpointDriftWitness _ _ (ResponseDrift _ _ (ShapeMismatch _))) = \"COMPAT_ERR:ENDPOINT_RESPONSE_SCHEMA_SHAPE_MISMATCH\"",
        "... | inr (EndpointDriftWitness _ _ (BodySchemaDrift _ _ _)) = \"COMPAT_ERR:ENDPOINT_BODY_SCHEMA_DRIFT\"",
        "... | inr (EndpointDriftWitness _ _ (ResponseDrift _ _ _)) = \"COMPAT_ERR:ENDPOINT_RESPONSE_SCHEMA_DRIFT\"",
        "... | inr (EndpointDriftWitness _ _ _) = \"COMPAT_ERR:ENDPOINT_DRIFT\"",
        "",
        "driftCtxK1 : ∀ {a₀ a₁} → Drift a₀ a₁ → String",
        "driftCtxK1 (ComponentRemoved _ _) = \"component\"",
        "driftCtxK1 (ComponentDriftWitness _ _ _) = \"component\"",
        "driftCtxK1 (EndpointRemoved _ _) = \"method\"",
        "driftCtxK1 (EndpointDriftWitness _ _ _) = \"method\"",
        "",
        "driftCtxV1 : ∀ {a₀ a₁} → Drift a₀ a₁ → String",
        "driftCtxV1 (ComponentRemoved {k = k} _ _) = k",
        "driftCtxV1 (ComponentDriftWitness {k = k} _ _ _) = k",
        "driftCtxV1 (EndpointRemoved {m = m} _ _) = methodToString m",
        "driftCtxV1 (EndpointDriftWitness {m = m} _ _ _) = methodToString m",
        "",
        "driftCtxK2 : ∀ {a₀ a₁} → Drift a₀ a₁ → String",
        "driftCtxK2 (ComponentRemoved _ _) = \"\"",
        "driftCtxK2 (ComponentDriftWitness _ _ d) = schemaDriftCtxK d",
        "driftCtxK2 (EndpointRemoved _ _) = \"path\"",
        "driftCtxK2 (EndpointDriftWitness _ _ (RouteChanged _)) = \"drift\"",
        "driftCtxK2 (EndpointDriftWitness _ _ (MethodChanged _)) = \"drift\"",
        "driftCtxK2 (EndpointDriftWitness _ _ (ParameterRemoved _ _)) = \"parameter\"",
        "driftCtxK2 (EndpointDriftWitness _ _ (RequiredParameterAdded _ _ _ _ _ _)) = \"parameter\"",
        "driftCtxK2 (EndpointDriftWitness _ _ (NewRequiredParameter _ _ _)) = \"parameter\"",
        "driftCtxK2 (EndpointDriftWitness _ _ (ParameterSchemaChanged _ _ _ _ _)) = \"parameter\"",
        "driftCtxK2 (EndpointDriftWitness _ _ (BodySchemaDrift _ _ d)) = schemaDriftCtxK d",
        "driftCtxK2 (EndpointDriftWitness _ _ (ResponseRemoved _ _)) = \"response_status\"",
        "driftCtxK2 (EndpointDriftWitness _ _ (ResponseDrift _ _ d)) = schemaDriftCtxK d",
        "",
        "driftCtxV2 : ∀ {a₀ a₁} → Drift a₀ a₁ → String",
        "driftCtxV2 (ComponentRemoved _ _) = \"\"",
        "driftCtxV2 (ComponentDriftWitness _ _ d) = schemaDriftCtxV d",
        "driftCtxV2 (EndpointRemoved {r = r} _ _) = pathHint r",
        "driftCtxV2 (EndpointDriftWitness _ _ (RouteChanged _)) = \"route_changed\"",
        "driftCtxV2 (EndpointDriftWitness _ _ (MethodChanged _)) = \"method_changed\"",
        "driftCtxV2 (EndpointDriftWitness _ _ (ParameterRemoved {k = k} _ _)) = k",
        "driftCtxV2 (EndpointDriftWitness _ _ (RequiredParameterAdded {p₀ = p₀} _ _ _ _ _ _)) = Parameter.name p₀",
        "driftCtxV2 (EndpointDriftWitness _ _ (NewRequiredParameter {k = k} _ _ _)) = k",
        "driftCtxV2 (EndpointDriftWitness _ _ (ParameterSchemaChanged {p₀ = p₀} _ _ _ _ _)) = Parameter.name p₀",
        "driftCtxV2 (EndpointDriftWitness _ _ (BodySchemaDrift _ _ d)) = schemaDriftCtxV d",
        "driftCtxV2 (EndpointDriftWitness _ _ (ResponseRemoved {st = st} _ _)) = statusToString st",
        "driftCtxV2 (EndpointDriftWitness _ _ (ResponseDrift {st = st} _ _ d)) = schemaDriftCtxV d",
        "",
        "compatCtxK1 : String",
        "compatCtxK1 with oldWF | newWF",
        "... | inr _ | _ = \"\"",
        "... | _ | inr _ = \"\"",
        f"... | inl wfOld | inl wfNew with API⊑? {old_api_name} {new_api_name} wfOld wfNew",
        "... | inl _ = \"\"",
        "... | inr d = driftCtxK1 d",
        "",
        "compatCtxV1 : String",
        "compatCtxV1 with oldWF | newWF",
        "... | inr _ | _ = \"\"",
        "... | _ | inr _ = \"\"",
        f"... | inl wfOld | inl wfNew with API⊑? {old_api_name} {new_api_name} wfOld wfNew",
        "... | inl _ = \"\"",
        "... | inr d = driftCtxV1 d",
        "",
        "compatCtxK2 : String",
        "compatCtxK2 with oldWF | newWF",
        "... | inr _ | _ = \"\"",
        "... | _ | inr _ = \"\"",
        f"... | inl wfOld | inl wfNew with API⊑? {old_api_name} {new_api_name} wfOld wfNew",
        "... | inl _ = \"\"",
        "... | inr d = driftCtxK2 d",
        "",
        "compatCtxV2 : String",
        "compatCtxV2 with oldWF | newWF",
        "... | inr _ | _ = \"\"",
        "... | _ | inr _ = \"\"",
        f"... | inl wfOld | inl wfNew with API⊑? {old_api_name} {new_api_name} wfOld wfNew",
        "... | inl _ = \"\"",
        "... | inr d = driftCtxV2 d",
        "",
        "postulate",
        "  printResult : String → String → String → String → String → IO Unit.⊤",
        "{-# FOREIGN GHC import qualified Data.Text.IO as T #-}",
        "{-# COMPILE GHC printResult = \\tag k1 v1 k2 v2 -> T.putStrLn tag >> T.putStrLn k1 >> T.putStrLn v1 >> T.putStrLn k2 >> T.putStrLn v2 >> return () #-}",
        "",
        "main : IO Unit.⊤",
        "main = printResult compatTag compatCtxK1 compatCtxV1 compatCtxK2 compatCtxV2",
    ]

    source = "\n".join(lines)

    return source
