def print_compat_runner_module_source(
    module_name: str = "Generated.RunCompatCheck",
    old_api_module_name: str = "Generated.GeneratedOldAPI",
    new_api_module_name: str = "Generated.GeneratedNewAPI",
    old_api_name: str = "OldAPI",
    new_api_name: str = "NewAPI",
) -> str:
    lines = [
        f"module {module_name} where",
        "",
        "open import Agda.Builtin.IO",
        "import Agda.Builtin.Unit as Unit",
        "",
        "open import Prelude using (String; _∔_; inl; inr)",
        f"open import {old_api_module_name}",
        f"open import {new_api_module_name}",
        "open import WellFormed.Core",
        "open import WellFormed.Decidable",
        "open import WellFormed.IllFormed",
        "open import Semantics.APIRefinement",
        "open import Semantics.DecidableRefinement",
        "open import Semantics.Drift",
        "",
        f"oldWF : WFAPI {old_api_name} ∔ APIIllFormed {old_api_name}",
        f"oldWF = WFAPI? {old_api_name}",
        "",
        f"newWF : WFAPI {new_api_name} ∔ APIIllFormed {new_api_name}",
        f"newWF = WFAPI? {new_api_name}",
        "",
        "compatTag : String",
        "compatTag with oldWF | newWF",
        "... | inr _ | _ = \"COMPAT_CHECK_ERROR:OLD_SPEC_NOT_WF\"",
        "... | _ | inr _ = \"COMPAT_CHECK_ERROR:NEW_SPEC_NOT_WF\"",
        f"... | inl wfOld | inl wfNew with API⊑? {old_api_name} {new_api_name} wfOld wfNew",
        "... | inl _ = \"COMPAT_OK\"",
        "... | inr (ComponentRemoved _ _) = \"COMPAT_ERR:COMPONENT_REMOVED\"",
        "... | inr (ComponentDriftWitness _ _ _) = \"COMPAT_ERR:COMPONENT_DRIFT\"",
        "... | inr (EndpointRemoved _ _) = \"COMPAT_ERR:ENDPOINT_REMOVED\"",
        "... | inr (EndpointDriftWitness _ _ _) = \"COMPAT_ERR:ENDPOINT_DRIFT\"",
        "",
        "postulate",
        "  printResult : String → String → String → String → String → IO Unit.⊤",
        "{-# FOREIGN GHC import qualified Data.Text.IO as T #-}",
        "{-# COMPILE GHC printResult = \\tag k1 v1 k2 v2 -> T.putStrLn tag >> T.putStrLn k1 >> T.putStrLn v1 >> T.putStrLn k2 >> T.putStrLn v2 >> return () #-}",
        "",
        "main : IO Unit.⊤",
        "main = printResult compatTag \"\" \"\" \"\" \"\"",
    ]

    source = "\n".join(lines)

    return source
