def print_wf_runner_module_source(
    module_name: str = "Generated.RunWFCheck",
    api_module_name: str = "Generated.GeneratedAPI",
) -> str:
    schema_patterns = [
        ("prim-has-items _ _", "PRIM_HAS_ITEMS"),
        ("prim-has-properties _ _ _ _", "PRIM_HAS_PROPERTIES"),
        ("prim-has-required _ _ _", "PRIM_HAS_REQUIRED"),
        ("array-missing-items _ _", "ARRAY_MISSING_ITEMS"),
        ("array-item-ill-formed _ _ _", "ARRAY_ITEM_ILL_FORMED"),
        ("array-has-properties _ _ _ _", "ARRAY_HAS_PROPERTIES"),
        ("array-has-required _ _ _", "ARRAY_HAS_REQUIRED"),
        ("object-has-items _ _", "OBJECT_HAS_ITEMS"),
        ("object-property-ill-formed _ _ _ _ _", "OBJECT_PROPERTY_ILL_FORMED"),
        ("object-missing-required _ _ _ _", "OBJECT_MISSING_REQUIRED"),
        ("object-duplicate-properties _ _", "OBJECT_DUPLICATE_PROPERTIES"),
        ("object-duplicate-required _ _", "OBJECT_DUPLICATE_REQUIRED"),
    ]

    lines = [
        f"module {module_name} where",
        "",
        "open import Agda.Builtin.IO",
        "import Agda.Builtin.Unit as Unit",
        "",
        "open import Prelude using (String; _∔_; inl; inr)",
        "open import Syntax.Syntax",
        f"open import {api_module_name}",
        "open import WellFormed.Core",
        "open import WellFormed.Decidable",
        "open import WellFormed.IllFormed",
        "",
        "wfResult : WFAPI GeneratedAPI ∔ APIIllFormed GeneratedAPI",
        "wfResult = WFAPI? GeneratedAPI",
        "",
        "statusToString : Status → String",
        "statusToString OK = \"OK\"",
        "statusToString BadRequest = \"BadRequest\"",
        "statusToString NotFound = \"NotFound\"",
        "statusToString NoContent = \"NoContent\"",
        "",
        "componentSchemaErrTag : ∀ {s} → SchemaIllFormed s → String",
    ]

    for pat, tag in schema_patterns:
        lines.append(f"componentSchemaErrTag ({pat}) = \"WF_ERR:API_COMPONENT_SCHEMA_{tag}\"")

    lines.extend([
        "",
        "bodySchemaErrTag : ∀ {s} → SchemaIllFormed s → String",
    ])

    for pat, tag in schema_patterns:
        lines.append(f"bodySchemaErrTag ({pat}) = \"WF_ERR:API_ENDPOINT_BODY_SCHEMA_{tag}\"")

    lines.extend([
        "",
        "responseSchemaErrTag : ∀ {s} → SchemaIllFormed s → String",
    ])

    for pat, tag in schema_patterns:
        lines.append(f"responseSchemaErrTag ({pat}) = \"WF_ERR:API_ENDPOINT_RESPONSE_SCHEMA_{tag}\"")

    lines.extend([
        "",
        "schemaCtxK : ∀ {s} → SchemaIllFormed s → String",
        "schemaCtxK (prim-has-items _ _) = \"\"",
        "schemaCtxK (prim-has-properties _ _ _ _) = \"property\"",
        "schemaCtxK (prim-has-required _ _ _) = \"required\"",
        "schemaCtxK (array-missing-items _ _) = \"\"",
        "schemaCtxK (array-item-ill-formed _ _ ill) = schemaCtxK ill",
        "schemaCtxK (array-has-properties _ _ _ _) = \"property\"",
        "schemaCtxK (array-has-required _ _ _) = \"required\"",
        "schemaCtxK (object-has-items _ _) = \"\"",
        "schemaCtxK (object-property-ill-formed _ _ _ _ ill) = \"property\"",
        "schemaCtxK (object-missing-required _ _ _ _) = \"missing_required\"",
        "schemaCtxK (object-duplicate-properties _ _) = \"\"",
        "schemaCtxK (object-duplicate-required _ _) = \"\"",
        "",
        "schemaCtxV : ∀ {s} → SchemaIllFormed s → String",
        "schemaCtxV (prim-has-items _ _) = \"\"",
        "schemaCtxV (prim-has-properties _ k _ _) = k",
        "schemaCtxV (prim-has-required _ k _) = k",
        "schemaCtxV (array-missing-items _ _) = \"\"",
        "schemaCtxV (array-item-ill-formed _ _ ill) = schemaCtxV ill",
        "schemaCtxV (array-has-properties _ k _ _) = k",
        "schemaCtxV (array-has-required _ k _) = k",
        "schemaCtxV (object-has-items _ _) = \"\"",
        "schemaCtxV (object-property-ill-formed _ k _ _ ill) = k",
        "schemaCtxV (object-missing-required _ k _ _) = k",
        "schemaCtxV (object-duplicate-properties _ _) = \"\"",
        "schemaCtxV (object-duplicate-required _ _) = \"\"",
        "",
        "pathCtxK : ∀ {p ps} → PathIllFormed p ps → String",
        "pathCtxK (duplicate-placeholder _) = \"\"",
        "pathCtxK (placeholder-not-declared _ _ _) = \"placeholder\"",
        "pathCtxK (orphan-path-parameter _ _ _) = \"orphan_parameter\"",
        "",
        "pathCtxV : ∀ {p ps} → PathIllFormed p ps → String",
        "pathCtxV (duplicate-placeholder _) = \"\"",
        "pathCtxV (placeholder-not-declared x _ _) = x",
        "pathCtxV (orphan-path-parameter x _ _) = x",
        "",
        "endpointCtxK1 : ∀ {e} → EndpointIllFormed e → String",
        "endpointCtxK1 (endpoint-path-ill-formed illP) = pathCtxK illP",
        "endpointCtxK1 (endpoint-parameter-ill-formed p _ _) = \"parameter\"",
        "endpointCtxK1 (endpoint-duplicate-parameters _) = \"\"",
        "endpointCtxK1 (endpoint-body-ill-formed (post-body-ill-formed illS)) = schemaCtxK illS",
        "endpointCtxK1 (endpoint-body-ill-formed (put-body-ill-formed illS)) = schemaCtxK illS",
        "endpointCtxK1 (endpoint-body-ill-formed (patch-body-ill-formed illS)) = schemaCtxK illS",
        "endpointCtxK1 (endpoint-response-ill-formed (response _ _) _ (response-schema-ill-formed _)) = \"status\"",
        "endpointCtxK1 (endpoint-duplicate-statuses _) = \"\"",
        "",
        "endpointCtxV1 : ∀ {e} → EndpointIllFormed e → String",
        "endpointCtxV1 (endpoint-path-ill-formed illP) = pathCtxV illP",
        "endpointCtxV1 (endpoint-parameter-ill-formed p _ _) = Parameter.name p",
        "endpointCtxV1 (endpoint-duplicate-parameters _) = \"\"",
        "endpointCtxV1 (endpoint-body-ill-formed (post-body-ill-formed illS)) = schemaCtxV illS",
        "endpointCtxV1 (endpoint-body-ill-formed (put-body-ill-formed illS)) = schemaCtxV illS",
        "endpointCtxV1 (endpoint-body-ill-formed (patch-body-ill-formed illS)) = schemaCtxV illS",
        "endpointCtxV1 (endpoint-response-ill-formed (response st _) _ (response-schema-ill-formed _)) = statusToString st",
        "endpointCtxV1 (endpoint-duplicate-statuses _) = \"\"",
        "",
        "endpointCtxK2 : ∀ {e} → EndpointIllFormed e → String",
        "endpointCtxK2 (endpoint-path-ill-formed _) = \"\"",
        "endpointCtxK2 (endpoint-parameter-ill-formed _ _ _) = \"\"",
        "endpointCtxK2 (endpoint-duplicate-parameters _) = \"\"",
        "endpointCtxK2 (endpoint-body-ill-formed (post-body-ill-formed _)) = \"\"",
        "endpointCtxK2 (endpoint-body-ill-formed (put-body-ill-formed _)) = \"\"",
        "endpointCtxK2 (endpoint-body-ill-formed (patch-body-ill-formed _)) = \"\"",
        "endpointCtxK2 (endpoint-response-ill-formed (response _ _) _ (response-schema-ill-formed illS)) = schemaCtxK illS",
        "endpointCtxK2 (endpoint-duplicate-statuses _) = \"\"",
        "",
        "endpointCtxV2 : ∀ {e} → EndpointIllFormed e → String",
        "endpointCtxV2 (endpoint-path-ill-formed _) = \"\"",
        "endpointCtxV2 (endpoint-parameter-ill-formed _ _ _) = \"\"",
        "endpointCtxV2 (endpoint-duplicate-parameters _) = \"\"",
        "endpointCtxV2 (endpoint-body-ill-formed (post-body-ill-formed _)) = \"\"",
        "endpointCtxV2 (endpoint-body-ill-formed (put-body-ill-formed _)) = \"\"",
        "endpointCtxV2 (endpoint-body-ill-formed (patch-body-ill-formed _)) = \"\"",
        "endpointCtxV2 (endpoint-response-ill-formed (response _ _) _ (response-schema-ill-formed illS)) = schemaCtxV illS",
        "endpointCtxV2 (endpoint-duplicate-statuses _) = \"\"",
        "",
        "apiErrTag : APIIllFormed GeneratedAPI → String",
        "apiErrTag (api-component-ill-formed _ _ _ illS) = componentSchemaErrTag illS",
        "apiErrTag (api-duplicate-components _) = \"WF_ERR:API_DUPLICATE_COMPONENTS\"",
        "apiErrTag (api-duplicate-endpoints _) = \"WF_ERR:API_DUPLICATE_ENDPOINTS\"",
        "apiErrTag (api-endpoint-ill-formed _ _ illE) with illE",
        "... | endpoint-path-ill-formed _ = \"WF_ERR:API_ENDPOINT_PATH_ILL_FORMED\"",
        "... | endpoint-parameter-ill-formed _ _ _ = \"WF_ERR:API_ENDPOINT_PARAMETER_ILL_FORMED\"",
        "... | endpoint-duplicate-parameters _ = \"WF_ERR:API_ENDPOINT_DUPLICATE_PARAMETERS\"",
        "... | endpoint-body-ill-formed (post-body-ill-formed illS) = bodySchemaErrTag illS",
        "... | endpoint-body-ill-formed (put-body-ill-formed illS) = bodySchemaErrTag illS",
        "... | endpoint-body-ill-formed (patch-body-ill-formed illS) = bodySchemaErrTag illS",
        "... | endpoint-response-ill-formed _ _ (response-schema-ill-formed illS) = responseSchemaErrTag illS",
        "... | endpoint-duplicate-statuses _ = \"WF_ERR:API_ENDPOINT_DUPLICATE_STATUSES\"",
        "",
        "apiCtxK1 : APIIllFormed GeneratedAPI → String",
        "apiCtxK1 (api-component-ill-formed _ _ _ _) = \"component\"",
        "apiCtxK1 (api-duplicate-components _) = \"\"",
        "apiCtxK1 (api-duplicate-endpoints _) = \"\"",
        "apiCtxK1 (api-endpoint-ill-formed _ _ illE) = endpointCtxK1 illE",
        "",
        "apiCtxV1 : APIIllFormed GeneratedAPI → String",
        "apiCtxV1 (api-component-ill-formed k _ _ _) = k",
        "apiCtxV1 (api-duplicate-components _) = \"\"",
        "apiCtxV1 (api-duplicate-endpoints _) = \"\"",
        "apiCtxV1 (api-endpoint-ill-formed _ _ illE) = endpointCtxV1 illE",
        "",
        "apiCtxK2 : APIIllFormed GeneratedAPI → String",
        "apiCtxK2 (api-component-ill-formed _ _ _ illS) = schemaCtxK illS",
        "apiCtxK2 (api-duplicate-components _) = \"\"",
        "apiCtxK2 (api-duplicate-endpoints _) = \"\"",
        "apiCtxK2 (api-endpoint-ill-formed _ _ illE) = endpointCtxK2 illE",
        "",
        "apiCtxV2 : APIIllFormed GeneratedAPI → String",
        "apiCtxV2 (api-component-ill-formed _ _ _ illS) = schemaCtxV illS",
        "apiCtxV2 (api-duplicate-components _) = \"\"",
        "apiCtxV2 (api-duplicate-endpoints _) = \"\"",
        "apiCtxV2 (api-endpoint-ill-formed _ _ illE) = endpointCtxV2 illE",
        "",
        "resultTag : String",
        "resultTag with wfResult",
        "... | inl _ = \"WF_OK\"",
        "... | inr ill = apiErrTag ill",
        "",
        "resultContext : String",
        "resultContext with wfResult",
        "... | inl _ = \"\"",
        "... | inr ill = apiCtxK1 ill",
        "",
        "resultValue : String",
        "resultValue with wfResult",
        "... | inl _ = \"\"",
        "... | inr ill = apiCtxV1 ill",
        "",
        "resultContext2 : String",
        "resultContext2 with wfResult",
        "... | inl _ = \"\"",
        "... | inr ill = apiCtxK2 ill",
        "",
        "resultValue2 : String",
        "resultValue2 with wfResult",
        "... | inl _ = \"\"",
        "... | inr ill = apiCtxV2 ill",
        "",
        "postulate",
        "  printResult : String → String → String → String → String → IO Unit.⊤",
        "{-# FOREIGN GHC import qualified Data.Text.IO as T #-}",
        "{-# COMPILE GHC printResult = \\tag k1 v1 k2 v2 -> T.putStrLn tag >> T.putStrLn k1 >> T.putStrLn v1 >> T.putStrLn k2 >> T.putStrLn v2 >> return () #-}",
        "",
        "main : IO Unit.⊤",
        "main = printResult resultTag resultContext resultValue resultContext2 resultValue2",
    ])

    return "\n".join(lines)